// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
export { default } from 'D:/MyWeb/kaiyuan/lighting-design/node_modules/.pnpm/dumi@2.4.20_@babel+core@7.2_8fcca37068ba439da87ed8cf725b1e33/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
=======
export { default } from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.19_es_oqokus36eealj6kz36sgvripbq/node_modules/dumi/theme-default/slots/NavbarExtra/index.js';
>>>>>>> a141cd2112073a4c0e34736737dbba45a52298e1
