// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/.pnpm/dumi@2.4.20_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.20_es_szxesmxkh2q7ac77utcq7u5itm/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/.pnpm/dumi@2.4.20_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.20_es_szxesmxkh2q7ac77utcq7u5itm/node_modules/dumi/theme-default/slots/SearchBar/index.js';
