// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excel-import/index.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excel-import/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/table-export/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/table-export/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/big-screen/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/big-screen/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=frontmatter';
import { demoIndex as dmi4 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=frontmatter';
import { demoIndex as dmi5 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=frontmatter';
import { demoIndex as dmi6 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=frontmatter';
import { demoIndex as dmi7 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=frontmatter';
import { demoIndex as dmi8 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=frontmatter';
import { demoIndex as dmi9 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=frontmatter';
import { demoIndex as dmi10 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi11 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=frontmatter';
import { demoIndex as dmi12 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=frontmatter';
import { demoIndex as dmi13 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=frontmatter';
import { demoIndex as dmi14 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=frontmatter';
import { demoIndex as dmi15 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=frontmatter';
import { demoIndex as dmi16 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=frontmatter';
import { demoIndex as dmi17 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=frontmatter';
import { demoIndex as dmi18 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-captcha-button/index.md?type=frontmatter';
import { demoIndex as dmi19 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-captcha-button/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-card-group/index.md?type=frontmatter';
import { demoIndex as dmi20 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-card-group/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-collapse-card/index.md?type=frontmatter';
import { demoIndex as dmi21 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-collapse-card/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-descriptions/index.md?type=frontmatter';
import { demoIndex as dmi22 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-descriptions/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-drawer-form/index.md?type=frontmatter';
import { demoIndex as dmi23 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-drawer-form/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-echarts/index.md?type=frontmatter';
import { demoIndex as dmi24 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-echarts/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-edit-table/index.md?type=frontmatter';
import { demoIndex as dmi25 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-edit-table/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-ellipsis-text/index.md?type=frontmatter';
import { demoIndex as dmi26 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-ellipsis-text/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-file-viewer/index.md?type=frontmatter';
import { demoIndex as dmi27 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-file-viewer/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-address/index.md?type=frontmatter';
import { demoIndex as dmi28 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-address/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-auto-complete/index.md?type=frontmatter';
import { demoIndex as dmi29 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-auto-complete/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-captcha/index.md?type=frontmatter';
import { demoIndex as dmi30 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-captcha/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-cascader/index.md?type=frontmatter';
import { demoIndex as dmi31 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-cascader/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-checkbox/index.md?type=frontmatter';
import { demoIndex as dmi32 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-checkbox/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-color/index.md?type=frontmatter';
import { demoIndex as dmi33 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-color/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-date/index.md?type=frontmatter';
import { demoIndex as dmi34 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-date/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-icon/index.md?type=frontmatter';
import { demoIndex as dmi35 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-icon/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-input/index.md?type=frontmatter';
import { demoIndex as dmi36 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-input/index.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-mentions/index.md?type=frontmatter';
import { demoIndex as dmi37 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-mentions/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number-range/index.md?type=frontmatter';
import { demoIndex as dmi38 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number-range/index.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number/index.md?type=frontmatter';
import { demoIndex as dmi39 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-password/index.md?type=frontmatter';
import { demoIndex as dmi40 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-password/index.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-radio/index.md?type=frontmatter';
import { demoIndex as dmi41 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-radio/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-rate/index.md?type=frontmatter';
import { demoIndex as dmi42 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-rate/index.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-segmented/index.md?type=frontmatter';
import { demoIndex as dmi43 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-segmented/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-select/index.md?type=frontmatter';
import { demoIndex as dmi44 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-select/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-slider/index.md?type=frontmatter';
import { demoIndex as dmi45 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-slider/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-switch/index.md?type=frontmatter';
import { demoIndex as dmi46 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-switch/index.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-textarea/index.md?type=frontmatter';
import { demoIndex as dmi47 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-textarea/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-time/index.md?type=frontmatter';
import { demoIndex as dmi48 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-time/index.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-transfer/index.md?type=frontmatter';
import { demoIndex as dmi49 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-transfer/index.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-tree-select/index.md?type=frontmatter';
import { demoIndex as dmi50 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-tree-select/index.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-upload/index.md?type=frontmatter';
import { demoIndex as dmi51 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-upload/index.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item/index.md?type=frontmatter';
import { demoIndex as dmi52 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item/index.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form/index.md?type=frontmatter';
import { demoIndex as dmi53 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-form/index.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-h5-preview/index.md?type=frontmatter';
import { demoIndex as dmi54 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-h5-preview/index.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-highlight-text/index.md?type=frontmatter';
import { demoIndex as dmi55 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-highlight-text/index.md?type=demo-index';
import { frontmatter as fm56, toc as t56 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-list-form/index.md?type=frontmatter';
import { demoIndex as dmi56 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-list-form/index.md?type=demo-index';
import { frontmatter as fm57, toc as t57 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-list/index.md?type=frontmatter';
import { demoIndex as dmi57 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-list/index.md?type=demo-index';
import { frontmatter as fm58, toc as t58 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-modal-form/index.md?type=frontmatter';
import { demoIndex as dmi58 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-modal-form/index.md?type=demo-index';
import { frontmatter as fm59, toc as t59 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-number-roll/index.md?type=frontmatter';
import { demoIndex as dmi59 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-number-roll/index.md?type=demo-index';
import { frontmatter as fm60, toc as t60 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-query-form/index.md?type=frontmatter';
import { demoIndex as dmi60 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-query-form/index.md?type=demo-index';
import { frontmatter as fm61, toc as t61 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-right-menu/index.md?type=frontmatter';
import { demoIndex as dmi61 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-right-menu/index.md?type=demo-index';
import { frontmatter as fm62, toc as t62 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-scrollbar/index.md?type=frontmatter';
import { demoIndex as dmi62 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-scrollbar/index.md?type=demo-index';
import { frontmatter as fm63, toc as t63 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-seamless-scroll/index.md?type=frontmatter';
import { demoIndex as dmi63 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-seamless-scroll/index.md?type=demo-index';
import { frontmatter as fm64, toc as t64 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-skeleton/index.md?type=frontmatter';
import { demoIndex as dmi64 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-skeleton/index.md?type=demo-index';
import { frontmatter as fm65, toc as t65 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-slider-verify/index.md?type=frontmatter';
import { demoIndex as dmi65 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-slider-verify/index.md?type=demo-index';
import { frontmatter as fm66, toc as t66 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-steps-form/index.md?type=frontmatter';
import { demoIndex as dmi66 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-steps-form/index.md?type=demo-index';
import { frontmatter as fm67, toc as t67 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-table/index.md?type=frontmatter';
import { demoIndex as dmi67 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-table/index.md?type=demo-index';
import { frontmatter as fm68, toc as t68 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tag-group/index.md?type=frontmatter';
import { demoIndex as dmi68 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tag-group/index.md?type=demo-index';
import { frontmatter as fm69, toc as t69 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tianai-captcha/index.md?type=frontmatter';
import { demoIndex as dmi69 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tianai-captcha/index.md?type=demo-index';
import { frontmatter as fm70, toc as t70 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tree-table/index.md?type=frontmatter';
import { demoIndex as dmi70 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-tree-table/index.md?type=demo-index';
import { frontmatter as fm71, toc as t71 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-trigger/index.md?type=frontmatter';
import { demoIndex as dmi71 } from 'D:/MyWeb/kaiyuan/lighting-design/src/l-trigger/index.md?type=demo-index';

export const filesMeta = {
  'docs/scene/excel-import/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excel-import/index.md?type=text'),
  },
  'docs/scene/table-export/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/table-export/index.md?type=text'),
  },
  'docs/scene/big-screen/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/big-screen/index.md?type=text'),
  },
  'docs/scene/download/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=text'),
  },
  'docs/scene/mockjs/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=text'),
  },
  'docs/guide/performance': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=text'),
  },
  'docs/components/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=text'),
  },
  'docs/guide/get-start': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=text'),
  },
  'docs/guide/deploy': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=text'),
  },
  'docs/guide/thanks': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=text'),
  },
  'docs/guide/update': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=text'),
  },
  'docs/guide/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=text'),
  },
  'docs/hooks/start': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=text'),
  },
  'docs/scene/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=text'),
  },
  'docs/components': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=text'),
  },
  'docs/guide/faq': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=text'),
  },
  'docs/guide/que': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=text'),
  },
  'docs/record': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=text'),
  },
  'components/l-captcha-button/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__l-captcha-button" */'D:/MyWeb/kaiyuan/lighting-design/src/l-captcha-button/index.md?type=text'),
  },
  'components/l-card-group/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__l-card-group" */'D:/MyWeb/kaiyuan/lighting-design/src/l-card-group/index.md?type=text'),
  },
  'components/l-collapse-card/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__l-collapse-card" */'D:/MyWeb/kaiyuan/lighting-design/src/l-collapse-card/index.md?type=text'),
  },
  'components/l-descriptions/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__l-descriptions" */'D:/MyWeb/kaiyuan/lighting-design/src/l-descriptions/index.md?type=text'),
  },
  'components/l-drawer-form/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__l-drawer-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-drawer-form/index.md?type=text'),
  },
  'components/l-echarts/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__l-echarts" */'D:/MyWeb/kaiyuan/lighting-design/src/l-echarts/index.md?type=text'),
  },
  'components/l-edit-table/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__l-edit-table" */'D:/MyWeb/kaiyuan/lighting-design/src/l-edit-table/index.md?type=text'),
  },
  'components/l-ellipsis-text/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__l-ellipsis-text" */'D:/MyWeb/kaiyuan/lighting-design/src/l-ellipsis-text/index.md?type=text'),
  },
  'components/l-file-viewer/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__l-file-viewer" */'D:/MyWeb/kaiyuan/lighting-design/src/l-file-viewer/index.md?type=text'),
  },
  'components/l-form-item-address/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-address" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-address/index.md?type=text'),
  },
  'components/l-form-item-auto-complete/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-auto-complete" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-auto-complete/index.md?type=text'),
  },
  'components/l-form-item-captcha/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-captcha" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-captcha/index.md?type=text'),
  },
  'components/l-form-item-cascader/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-cascader" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-cascader/index.md?type=text'),
  },
  'components/l-form-item-checkbox/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-checkbox" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-checkbox/index.md?type=text'),
  },
  'components/l-form-item-color/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-color" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-color/index.md?type=text'),
  },
  'components/l-form-item-date/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-date" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-date/index.md?type=text'),
  },
  'components/l-form-item-icon/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-icon" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-icon/index.md?type=text'),
  },
  'components/l-form-item-input/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-input" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-input/index.md?type=text'),
  },
  'components/l-form-item-mentions/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-mentions" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-mentions/index.md?type=text'),
  },
  'components/l-form-item-number-range/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-number-range" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number-range/index.md?type=text'),
  },
  'components/l-form-item-number/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-number" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-number/index.md?type=text'),
  },
  'components/l-form-item-password/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-password" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-password/index.md?type=text'),
  },
  'components/l-form-item-radio/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-radio" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-radio/index.md?type=text'),
  },
  'components/l-form-item-rate/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-rate" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-rate/index.md?type=text'),
  },
  'components/l-form-item-segmented/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-segmented" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-segmented/index.md?type=text'),
  },
  'components/l-form-item-select/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-select" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-select/index.md?type=text'),
  },
  'components/l-form-item-slider/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-slider" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-slider/index.md?type=text'),
  },
  'components/l-form-item-switch/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-switch" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-switch/index.md?type=text'),
  },
  'components/l-form-item-textarea/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-textarea" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-textarea/index.md?type=text'),
  },
  'components/l-form-item-time/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-time" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-time/index.md?type=text'),
  },
  'components/l-form-item-transfer/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-transfer" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-transfer/index.md?type=text'),
  },
  'components/l-form-item-tree-select/index': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-tree-select" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-tree-select/index.md?type=text'),
  },
  'components/l-form-item-upload/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item-upload" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item-upload/index.md?type=text'),
  },
  'components/l-form-item/index': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__l-form-item" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form-item/index.md?type=text'),
  },
  'components/l-form/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__l-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-form/index.md?type=text'),
  },
  'components/l-h5-preview/index': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__l-h5-preview" */'D:/MyWeb/kaiyuan/lighting-design/src/l-h5-preview/index.md?type=text'),
  },
  'components/l-highlight-text/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__l-highlight-text" */'D:/MyWeb/kaiyuan/lighting-design/src/l-highlight-text/index.md?type=text'),
  },
  'components/l-list-form/index': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__l-list-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-list-form/index.md?type=text'),
  },
  'components/l-list/index': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__l-list" */'D:/MyWeb/kaiyuan/lighting-design/src/l-list/index.md?type=text'),
  },
  'components/l-modal-form/index': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__l-modal-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-modal-form/index.md?type=text'),
  },
  'components/l-number-roll/index': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__l-number-roll" */'D:/MyWeb/kaiyuan/lighting-design/src/l-number-roll/index.md?type=text'),
  },
  'components/l-query-form/index': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__l-query-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-query-form/index.md?type=text'),
  },
  'components/l-right-menu/index': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__l-right-menu" */'D:/MyWeb/kaiyuan/lighting-design/src/l-right-menu/index.md?type=text'),
  },
  'components/l-scrollbar/index': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__l-scrollbar" */'D:/MyWeb/kaiyuan/lighting-design/src/l-scrollbar/index.md?type=text'),
  },
  'components/l-seamless-scroll/index': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__l-seamless-scroll" */'D:/MyWeb/kaiyuan/lighting-design/src/l-seamless-scroll/index.md?type=text'),
  },
  'components/l-skeleton/index': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__l-skeleton" */'D:/MyWeb/kaiyuan/lighting-design/src/l-skeleton/index.md?type=text'),
  },
  'components/l-slider-verify/index': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__l-slider-verify" */'D:/MyWeb/kaiyuan/lighting-design/src/l-slider-verify/index.md?type=text'),
  },
  'components/l-steps-form/index': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__l-steps-form" */'D:/MyWeb/kaiyuan/lighting-design/src/l-steps-form/index.md?type=text'),
  },
  'components/l-table/index': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__l-table" */'D:/MyWeb/kaiyuan/lighting-design/src/l-table/index.md?type=text'),
  },
  'components/l-tag-group/index': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__l-tag-group" */'D:/MyWeb/kaiyuan/lighting-design/src/l-tag-group/index.md?type=text'),
  },
  'components/l-tianai-captcha/index': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__l-tianai-captcha" */'D:/MyWeb/kaiyuan/lighting-design/src/l-tianai-captcha/index.md?type=text'),
  },
  'components/l-tree-table/index': {
    frontmatter: fm70,
    toc: t70,
    demoIndex: dmi70,
    textGetter: () => import(/* webpackChunkName: "meta__l-tree-table" */'D:/MyWeb/kaiyuan/lighting-design/src/l-tree-table/index.md?type=text'),
  },
  'components/l-trigger/index': {
    frontmatter: fm71,
    toc: t71,
    demoIndex: dmi71,
    textGetter: () => import(/* webpackChunkName: "meta__l-trigger" */'D:/MyWeb/kaiyuan/lighting-design/src/l-trigger/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
