// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excelImport/index.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excelImport/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/tableExport/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/tableExport/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/bigScreen/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/bigScreen/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=frontmatter';
import { demoIndex as dmi4 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=frontmatter';
import { demoIndex as dmi5 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=frontmatter';
import { demoIndex as dmi6 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=frontmatter';
import { demoIndex as dmi7 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=frontmatter';
import { demoIndex as dmi8 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=frontmatter';
import { demoIndex as dmi9 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=frontmatter';
import { demoIndex as dmi10 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi11 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=frontmatter';
import { demoIndex as dmi12 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=frontmatter';
import { demoIndex as dmi13 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=frontmatter';
import { demoIndex as dmi14 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=frontmatter';
import { demoIndex as dmi15 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=frontmatter';
import { demoIndex as dmi16 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=frontmatter';
import { demoIndex as dmi17 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=frontmatter';
import { demoIndex as dmi18 } from 'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CaptchaButton/index.md?type=frontmatter';
import { demoIndex as dmi19 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CaptchaButton/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CardGroup/index.md?type=frontmatter';
import { demoIndex as dmi20 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CardGroup/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CollapseCard/index.md?type=frontmatter';
import { demoIndex as dmi21 } from 'D:/MyWeb/kaiyuan/lighting-design/src/CollapseCard/index.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ColorPick/index.md?type=frontmatter';
import { demoIndex as dmi22 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ColorPick/index.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Descriptions/index.md?type=frontmatter';
import { demoIndex as dmi23 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Descriptions/index.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from 'D:/MyWeb/kaiyuan/lighting-design/src/DrawerForm/index.md?type=frontmatter';
import { demoIndex as dmi24 } from 'D:/MyWeb/kaiyuan/lighting-design/src/DrawerForm/index.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Echarts/index.md?type=frontmatter';
import { demoIndex as dmi25 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Echarts/index.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from 'D:/MyWeb/kaiyuan/lighting-design/src/EditTable/index.md?type=frontmatter';
import { demoIndex as dmi26 } from 'D:/MyWeb/kaiyuan/lighting-design/src/EditTable/index.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from 'D:/MyWeb/kaiyuan/lighting-design/src/EllipsisText/index.md?type=frontmatter';
import { demoIndex as dmi27 } from 'D:/MyWeb/kaiyuan/lighting-design/src/EllipsisText/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FileViewer/index.md?type=frontmatter';
import { demoIndex as dmi28 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FileViewer/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Form/index.md?type=frontmatter';
import { demoIndex as dmi29 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Form/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItem/index.md?type=frontmatter';
import { demoIndex as dmi30 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItem/index.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAddress/index.md?type=frontmatter';
import { demoIndex as dmi31 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAddress/index.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAutoComplete/index.md?type=frontmatter';
import { demoIndex as dmi32 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAutoComplete/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCaptcha/index.md?type=frontmatter';
import { demoIndex as dmi33 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCaptcha/index.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCascader/index.md?type=frontmatter';
import { demoIndex as dmi34 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCascader/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCheckbox/index.md?type=frontmatter';
import { demoIndex as dmi35 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCheckbox/index.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemColor/index.md?type=frontmatter';
import { demoIndex as dmi36 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemColor/index.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemDatePicker/index.md?type=frontmatter';
import { demoIndex as dmi37 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemDatePicker/index.md?type=demo-index';
import { frontmatter as fm38, toc as t38 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemIcon/index.md?type=frontmatter';
import { demoIndex as dmi38 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemIcon/index.md?type=demo-index';
import { frontmatter as fm39, toc as t39 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemInput/index.md?type=frontmatter';
import { demoIndex as dmi39 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemInput/index.md?type=demo-index';
import { frontmatter as fm40, toc as t40 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemMentions/index.md?type=frontmatter';
import { demoIndex as dmi40 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemMentions/index.md?type=demo-index';
import { frontmatter as fm41, toc as t41 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumber/index.md?type=frontmatter';
import { demoIndex as dmi41 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumber/index.md?type=demo-index';
import { frontmatter as fm42, toc as t42 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumberRange/index.md?type=frontmatter';
import { demoIndex as dmi42 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumberRange/index.md?type=demo-index';
import { frontmatter as fm43, toc as t43 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemPassword/index.md?type=frontmatter';
import { demoIndex as dmi43 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemPassword/index.md?type=demo-index';
import { frontmatter as fm44, toc as t44 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRadio/index.md?type=frontmatter';
import { demoIndex as dmi44 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRadio/index.md?type=demo-index';
import { frontmatter as fm45, toc as t45 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRate/index.md?type=frontmatter';
import { demoIndex as dmi45 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRate/index.md?type=demo-index';
import { frontmatter as fm46, toc as t46 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSegmented/index.md?type=frontmatter';
import { demoIndex as dmi46 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSegmented/index.md?type=demo-index';
import { frontmatter as fm47, toc as t47 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSelect/index.md?type=frontmatter';
import { demoIndex as dmi47 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSelect/index.md?type=demo-index';
import { frontmatter as fm48, toc as t48 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSlider/index.md?type=frontmatter';
import { demoIndex as dmi48 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSlider/index.md?type=demo-index';
import { frontmatter as fm49, toc as t49 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSwitch/index.md?type=frontmatter';
import { demoIndex as dmi49 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSwitch/index.md?type=demo-index';
import { frontmatter as fm50, toc as t50 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTextArea/index.md?type=frontmatter';
import { demoIndex as dmi50 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTextArea/index.md?type=demo-index';
import { frontmatter as fm51, toc as t51 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTimePicker/index.md?type=frontmatter';
import { demoIndex as dmi51 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTimePicker/index.md?type=demo-index';
import { frontmatter as fm52, toc as t52 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTransfer/index.md?type=frontmatter';
import { demoIndex as dmi52 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTransfer/index.md?type=demo-index';
import { frontmatter as fm53, toc as t53 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTreeSelect/index.md?type=frontmatter';
import { demoIndex as dmi53 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTreeSelect/index.md?type=demo-index';
import { frontmatter as fm54, toc as t54 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemUpload/index.md?type=frontmatter';
import { demoIndex as dmi54 } from 'D:/MyWeb/kaiyuan/lighting-design/src/FormItemUpload/index.md?type=demo-index';
import { frontmatter as fm55, toc as t55 } from 'D:/MyWeb/kaiyuan/lighting-design/src/H5Preview/index.md?type=frontmatter';
import { demoIndex as dmi55 } from 'D:/MyWeb/kaiyuan/lighting-design/src/H5Preview/index.md?type=demo-index';
import { frontmatter as fm56, toc as t56 } from 'D:/MyWeb/kaiyuan/lighting-design/src/HighlightText/index.md?type=frontmatter';
import { demoIndex as dmi56 } from 'D:/MyWeb/kaiyuan/lighting-design/src/HighlightText/index.md?type=demo-index';
import { frontmatter as fm57, toc as t57 } from 'D:/MyWeb/kaiyuan/lighting-design/src/List/index.md?type=frontmatter';
import { demoIndex as dmi57 } from 'D:/MyWeb/kaiyuan/lighting-design/src/List/index.md?type=demo-index';
import { frontmatter as fm58, toc as t58 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ListForm/index.md?type=frontmatter';
import { demoIndex as dmi58 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ListForm/index.md?type=demo-index';
import { frontmatter as fm59, toc as t59 } from 'D:/MyWeb/kaiyuan/lighting-design/src/LoginForm/index.md?type=frontmatter';
import { demoIndex as dmi59 } from 'D:/MyWeb/kaiyuan/lighting-design/src/LoginForm/index.md?type=demo-index';
import { frontmatter as fm60, toc as t60 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ModalForm/index.md?type=frontmatter';
import { demoIndex as dmi60 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ModalForm/index.md?type=demo-index';
import { frontmatter as fm61, toc as t61 } from 'D:/MyWeb/kaiyuan/lighting-design/src/NumberRoll/index.md?type=frontmatter';
import { demoIndex as dmi61 } from 'D:/MyWeb/kaiyuan/lighting-design/src/NumberRoll/index.md?type=demo-index';
import { frontmatter as fm62, toc as t62 } from 'D:/MyWeb/kaiyuan/lighting-design/src/QueryForm/index.md?type=frontmatter';
import { demoIndex as dmi62 } from 'D:/MyWeb/kaiyuan/lighting-design/src/QueryForm/index.md?type=demo-index';
import { frontmatter as fm63, toc as t63 } from 'D:/MyWeb/kaiyuan/lighting-design/src/RightMenu/index.md?type=frontmatter';
import { demoIndex as dmi63 } from 'D:/MyWeb/kaiyuan/lighting-design/src/RightMenu/index.md?type=demo-index';
import { frontmatter as fm64, toc as t64 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ScrollBar/index.md?type=frontmatter';
import { demoIndex as dmi64 } from 'D:/MyWeb/kaiyuan/lighting-design/src/ScrollBar/index.md?type=demo-index';
import { frontmatter as fm65, toc as t65 } from 'D:/MyWeb/kaiyuan/lighting-design/src/SeamlessScroll/index.md?type=frontmatter';
import { demoIndex as dmi65 } from 'D:/MyWeb/kaiyuan/lighting-design/src/SeamlessScroll/index.md?type=demo-index';
import { frontmatter as fm66, toc as t66 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Skeleton/index.md?type=frontmatter';
import { demoIndex as dmi66 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Skeleton/index.md?type=demo-index';
import { frontmatter as fm67, toc as t67 } from 'D:/MyWeb/kaiyuan/lighting-design/src/SliderVerify/index.md?type=frontmatter';
import { demoIndex as dmi67 } from 'D:/MyWeb/kaiyuan/lighting-design/src/SliderVerify/index.md?type=demo-index';
import { frontmatter as fm68, toc as t68 } from 'D:/MyWeb/kaiyuan/lighting-design/src/StepsForm/index.md?type=frontmatter';
import { demoIndex as dmi68 } from 'D:/MyWeb/kaiyuan/lighting-design/src/StepsForm/index.md?type=demo-index';
import { frontmatter as fm69, toc as t69 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Table/index.md?type=frontmatter';
import { demoIndex as dmi69 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Table/index.md?type=demo-index';
import { frontmatter as fm70, toc as t70 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TagGroup/index.md?type=frontmatter';
import { demoIndex as dmi70 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TagGroup/index.md?type=demo-index';
import { frontmatter as fm71, toc as t71 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TianaiCaptcha/index.md?type=frontmatter';
import { demoIndex as dmi71 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TianaiCaptcha/index.md?type=demo-index';
import { frontmatter as fm72, toc as t72 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TreeTable/index.md?type=frontmatter';
import { demoIndex as dmi72 } from 'D:/MyWeb/kaiyuan/lighting-design/src/TreeTable/index.md?type=demo-index';
import { frontmatter as fm73, toc as t73 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Trigger/index.md?type=frontmatter';
import { demoIndex as dmi73 } from 'D:/MyWeb/kaiyuan/lighting-design/src/Trigger/index.md?type=demo-index';

export const filesMeta = {
  'docs/scene/excelImport/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/excelImport/index.md?type=text'),
  },
  'docs/scene/tableExport/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/tableExport/index.md?type=text'),
  },
  'docs/scene/bigScreen/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/bigScreen/index.md?type=text'),
  },
  'docs/scene/download/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/download/index.md?type=text'),
  },
  'docs/scene/mockjs/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/mockjs/index.md?type=text'),
  },
  'docs/guide/performance': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/performance.md?type=text'),
  },
  'docs/components/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/components/index.md?type=text'),
  },
  'docs/guide/get-start': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/get-start.md?type=text'),
  },
  'docs/guide/deploy': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/deploy.md?type=text'),
  },
  'docs/guide/thanks': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/thanks.md?type=text'),
  },
  'docs/guide/update': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/update.md?type=text'),
  },
  'docs/guide/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/index.md?type=text'),
  },
  'docs/hooks/start': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/hooks/start.md?type=text'),
  },
  'docs/scene/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/scene/index.md?type=text'),
  },
  'docs/components': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/components.md?type=text'),
  },
  'docs/guide/faq': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/faq.md?type=text'),
  },
  'docs/guide/que': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/guide/que.md?type=text'),
  },
  'docs/record': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/record.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/MyWeb/kaiyuan/lighting-design/docs/index.md?type=text'),
  },
  'components/CaptchaButton/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__CaptchaButton" */'D:/MyWeb/kaiyuan/lighting-design/src/CaptchaButton/index.md?type=text'),
  },
  'components/CardGroup/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__CardGroup" */'D:/MyWeb/kaiyuan/lighting-design/src/CardGroup/index.md?type=text'),
  },
  'components/CollapseCard/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__CollapseCard" */'D:/MyWeb/kaiyuan/lighting-design/src/CollapseCard/index.md?type=text'),
  },
  'components/ColorPick/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__ColorPick" */'D:/MyWeb/kaiyuan/lighting-design/src/ColorPick/index.md?type=text'),
  },
  'components/Descriptions/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__Descriptions" */'D:/MyWeb/kaiyuan/lighting-design/src/Descriptions/index.md?type=text'),
  },
  'components/DrawerForm/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__DrawerForm" */'D:/MyWeb/kaiyuan/lighting-design/src/DrawerForm/index.md?type=text'),
  },
  'components/Echarts/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__Echarts" */'D:/MyWeb/kaiyuan/lighting-design/src/Echarts/index.md?type=text'),
  },
  'components/EditTable/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__EditTable" */'D:/MyWeb/kaiyuan/lighting-design/src/EditTable/index.md?type=text'),
  },
  'components/EllipsisText/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__EllipsisText" */'D:/MyWeb/kaiyuan/lighting-design/src/EllipsisText/index.md?type=text'),
  },
  'components/FileViewer/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__FileViewer" */'D:/MyWeb/kaiyuan/lighting-design/src/FileViewer/index.md?type=text'),
  },
  'components/Form/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__Form" */'D:/MyWeb/kaiyuan/lighting-design/src/Form/index.md?type=text'),
  },
  'components/FormItem/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__FormItem" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItem/index.md?type=text'),
  },
  'components/FormItemAddress/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemAddress" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAddress/index.md?type=text'),
  },
  'components/FormItemAutoComplete/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemAutoComplete" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemAutoComplete/index.md?type=text'),
  },
  'components/FormItemCaptcha/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemCaptcha" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCaptcha/index.md?type=text'),
  },
  'components/FormItemCascader/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemCascader" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCascader/index.md?type=text'),
  },
  'components/FormItemCheckbox/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemCheckbox" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemCheckbox/index.md?type=text'),
  },
  'components/FormItemColor/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemColor" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemColor/index.md?type=text'),
  },
  'components/FormItemDatePicker/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemDatePicker" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemDatePicker/index.md?type=text'),
  },
  'components/FormItemIcon/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemIcon" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemIcon/index.md?type=text'),
  },
  'components/FormItemInput/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemInput" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemInput/index.md?type=text'),
  },
  'components/FormItemMentions/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemMentions" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemMentions/index.md?type=text'),
  },
  'components/FormItemNumber/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemNumber" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumber/index.md?type=text'),
  },
  'components/FormItemNumberRange/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemNumberRange" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemNumberRange/index.md?type=text'),
  },
  'components/FormItemPassword/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemPassword" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemPassword/index.md?type=text'),
  },
  'components/FormItemRadio/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemRadio" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRadio/index.md?type=text'),
  },
  'components/FormItemRate/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemRate" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemRate/index.md?type=text'),
  },
  'components/FormItemSegmented/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemSegmented" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSegmented/index.md?type=text'),
  },
  'components/FormItemSelect/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemSelect" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSelect/index.md?type=text'),
  },
  'components/FormItemSlider/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemSlider" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSlider/index.md?type=text'),
  },
  'components/FormItemSwitch/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemSwitch" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemSwitch/index.md?type=text'),
  },
  'components/FormItemTextArea/index': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemTextArea" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTextArea/index.md?type=text'),
  },
  'components/FormItemTimePicker/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemTimePicker" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTimePicker/index.md?type=text'),
  },
  'components/FormItemTransfer/index': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemTransfer" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTransfer/index.md?type=text'),
  },
  'components/FormItemTreeSelect/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemTreeSelect" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemTreeSelect/index.md?type=text'),
  },
  'components/FormItemUpload/index': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__FormItemUpload" */'D:/MyWeb/kaiyuan/lighting-design/src/FormItemUpload/index.md?type=text'),
  },
  'components/H5Preview/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__H5Preview" */'D:/MyWeb/kaiyuan/lighting-design/src/H5Preview/index.md?type=text'),
  },
  'components/HighlightText/index': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__HighlightText" */'D:/MyWeb/kaiyuan/lighting-design/src/HighlightText/index.md?type=text'),
  },
  'components/List/index': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__List" */'D:/MyWeb/kaiyuan/lighting-design/src/List/index.md?type=text'),
  },
  'components/ListForm/index': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__ListForm" */'D:/MyWeb/kaiyuan/lighting-design/src/ListForm/index.md?type=text'),
  },
  'components/LoginForm/index': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__LoginForm" */'D:/MyWeb/kaiyuan/lighting-design/src/LoginForm/index.md?type=text'),
  },
  'components/ModalForm/index': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__ModalForm" */'D:/MyWeb/kaiyuan/lighting-design/src/ModalForm/index.md?type=text'),
  },
  'components/NumberRoll/index': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__NumberRoll" */'D:/MyWeb/kaiyuan/lighting-design/src/NumberRoll/index.md?type=text'),
  },
  'components/QueryForm/index': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__QueryForm" */'D:/MyWeb/kaiyuan/lighting-design/src/QueryForm/index.md?type=text'),
  },
  'components/RightMenu/index': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__RightMenu" */'D:/MyWeb/kaiyuan/lighting-design/src/RightMenu/index.md?type=text'),
  },
  'components/ScrollBar/index': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__ScrollBar" */'D:/MyWeb/kaiyuan/lighting-design/src/ScrollBar/index.md?type=text'),
  },
  'components/SeamlessScroll/index': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__SeamlessScroll" */'D:/MyWeb/kaiyuan/lighting-design/src/SeamlessScroll/index.md?type=text'),
  },
  'components/Skeleton/index': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__Skeleton" */'D:/MyWeb/kaiyuan/lighting-design/src/Skeleton/index.md?type=text'),
  },
  'components/SliderVerify/index': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__SliderVerify" */'D:/MyWeb/kaiyuan/lighting-design/src/SliderVerify/index.md?type=text'),
  },
  'components/StepsForm/index': {
    frontmatter: fm68,
    toc: t68,
    demoIndex: dmi68,
    textGetter: () => import(/* webpackChunkName: "meta__StepsForm" */'D:/MyWeb/kaiyuan/lighting-design/src/StepsForm/index.md?type=text'),
  },
  'components/Table/index': {
    frontmatter: fm69,
    toc: t69,
    demoIndex: dmi69,
    textGetter: () => import(/* webpackChunkName: "meta__Table" */'D:/MyWeb/kaiyuan/lighting-design/src/Table/index.md?type=text'),
  },
  'components/TagGroup/index': {
    frontmatter: fm70,
    toc: t70,
    demoIndex: dmi70,
    textGetter: () => import(/* webpackChunkName: "meta__TagGroup" */'D:/MyWeb/kaiyuan/lighting-design/src/TagGroup/index.md?type=text'),
  },
  'components/TianaiCaptcha/index': {
    frontmatter: fm71,
    toc: t71,
    demoIndex: dmi71,
    textGetter: () => import(/* webpackChunkName: "meta__TianaiCaptcha" */'D:/MyWeb/kaiyuan/lighting-design/src/TianaiCaptcha/index.md?type=text'),
  },
  'components/TreeTable/index': {
    frontmatter: fm72,
    toc: t72,
    demoIndex: dmi72,
    textGetter: () => import(/* webpackChunkName: "meta__TreeTable" */'D:/MyWeb/kaiyuan/lighting-design/src/TreeTable/index.md?type=text'),
  },
  'components/Trigger/index': {
    frontmatter: fm73,
    toc: t73,
    demoIndex: dmi73,
    textGetter: () => import(/* webpackChunkName: "meta__Trigger" */'D:/MyWeb/kaiyuan/lighting-design/src/Trigger/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
