// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useSiteData } from 'dumi';
import { useLayoutEffect, type FC } from 'react';
import './nprogress.css';
import UserLoading from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.19_es_oqokus36eealj6kz36sgvripbq/node_modules/dumi/dist/client/pages/Loading';
import nprogress from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    };
  }, []);

  return <UserLoading />;
};

export default DumiLoading;
