// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/dumi/dist/client/theme-api/index.js';
