// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/MyWeb/KaiYuan/lighting-design-v2/node_modules/dumi/theme-default/slots/SearchResult/index.js';
